var express = require('express');
var router = express.Router();
var loginRouter = require('./login');
var kiosksRouter = require('./kiosks');
var settingsRouter = require('./settings');
var kioskSettingsRouter = require('./kiosk_settings');
var usersRouter = require('./users');
var userRolesRouter = require('./user_roles');
var rolesRouter = require('./roles');
var customerAccountsRouter = require('./customer_accounts');
var customerTypesRouter = require('./customer_types');
var salesChannelRouter = require('./sales_channels');
var parametersRouter = require('./parameters');
var samplingSitesRouter = require('./sampling_sites');
var kioskParametersRouter = require('./kiosk_parameters');
var readingsRouter = require('./readings');
var productCategoriesRouter = require('./product_categories');
var productMrpsRouter = require('./product_mrps');
var productsRouter = require('./products');
var receiptsRouter = require('./receipts');
var receiptLineItemsRouter = require('./receipt_line_items');

router.use('/login', loginRouter);
router.use('/kiosks', kiosksRouter);
router.use('/settings', settingsRouter);
router.use('/kiosk_settings', kioskSettingsRouter);
router.use('/users', usersRouter);
router.use('/user_roles', userRolesRouter);
router.use('/roles', rolesRouter);
router.use('/customer_accounts', customerAccountsRouter);
router.use('/customer_types', customerTypesRouter);
router.use('/sales_channels', salesChannelRouter);
router.use('/parameters', parametersRouter);
router.use('/sampling_sites', samplingSitesRouter);
router.use('/kiosk_parameters', kioskParametersRouter);
router.use('/readings', readingsRouter);
router.use('/product_categories', productCategoriesRouter);
router.use('/product_mrps', productMrpsRouter);
router.use('/products', productsRouter);
router.use('/receipts', receiptsRouter);
router.use('/receipt_line_items', receiptLineItemsRouter);

module.exports = router;
